module.exports = {
	UsuarioService: require("./usuario.service"),
	RolService: require("./rol.service"),
	VerificarToken: require("./verificarToken.service"),
	SucursalService: require("./sucursal.service"),
	EmpresaService: require("./empresa.service"),
	FileService: require("./files.service"),
	EgresoHostalService: require("./Hostal/egresoHostal.service"),
	IngresoHostalService: require("./Hostal/ingresoHostal.service"),
	ClienteService: require("./cliente.service"),
	CausaService: require("./Abogados/causa.service"),
	ContratoClienteAbogadoService: require("./Abogados/contratoClienteAbogado.service"),
	CuotasContratoAbogadoService: require("./Abogados/cuotasContratoAbogado.service"),
	AbogadoService: require("./Abogados/abogado.service"),
	EgresoFirmaService: require("./Abogados/egresoFirma.service"),
	RentacarService: require("./Rentacar/ingresosRentacar.service"),
	EgresoLubricentroService: require("./Lubricentro/egresoLubricentro.service"),
	IngresoLubricentroService: require("./Lubricentro/ingresoLubricentro.service"),
	EgresoRentacarService: require("./Rentacar/egresoRentacar.service"),
};
