module.exports = {
	UsuarioBusiness: require("./administracion/usuario.business"),
	RolBusiness: require("./administracion/rol.business"),
	EmpresaBusiness: require("./administracion/empresa.business"),
	SucursalBusiness: require("./administracion/sucursal.business"),
	EgresoHostalBusiness: require("./hostal/egresoHostal.business"),
	IngresoHostalBusiness: require("./hostal/ingresoHostal.business"),
	EgresoLubricentroBusiness: require("./lubricentro/egresoLubricentro.business"),
	IngresoLubricentroBusiness: require("./lubricentro/ingresoLubricentro.business"),
	ClienteBusiness: require("./administracion/cliente.business"),
	CausaBusiness: require("./abogados/causa.business"),
	ContratoClienteAbogadoBusiness: require("./abogados/contratoClienteAbogado.business"),
	CuotasContratoAbogadoBusiness: require("./abogados/cuotasContratoAbogados.business"),
	AbogadoBusiness: require("./abogados/abogado.business"),
	EgresoFirmaBusiness: require("./abogados/egresoFirma.business"),
	RentacarIngresosRequestBusiness: require("./rentacar/rentacarIngresosRequest.business.js"),
	EgresoRentacarBusiness: require("./rentacar/egresoRentacar.business"),
	ProyectoAgrofirmaBusiness: require("./agrofirma/proyectoAgrofirma.business"),
	BancoBusiness: require("./administracion/banco.business"),
	IngresoAgrofirmaBusiness: require("./agrofirma/ingresoAgrofirma.business"),
	EgresoAgrofirmaBusiness: require("./agrofirma/egresoAgrofirfma.business"),
	EgresoInmobiliariaBusiness: require("./inmobiliaria/egresoInmobiliaria.business"),
	IngresoInmobiliariaBusiness: require("./inmobiliaria/ingresoInmobiliaria.business"),
};
