module.exports = {
	Usuario: require("./administracion/usuario"),
	Rol: require("./administracion/rol"),
	Empresa: require("./administracion/empresa"),
	Sucursal: require("./administracion/sucursal"),
	EgresoHostal: require("./hostal/egresoHostal"),
	egresoLubricentro: require("./egresoLubricentro"),
	RespaldoEgreso: require("./respaldoEgreso"),
	EquipoAbogado: require("./firmaAbogados/equipoAbogado"),
	DetallePagoArriendo: require("./rentacar/detallePagoArriendo"),
	CuotaContrato: require("./firmaAbogados/cuotaContrato"),
	Usuario: require("./usuario"),
	Rol: require("./rol"),
	Empresa: require("./empresa"),
	Sucursal: require("./sucursal"),
	EgresoHostal: require("./egresoHostal"),
	EgresoLubricentro: require("./egresoLubricentro"),
	RespaldoEgreso: require("./respaldoEgreso"),
	EquipoAbogado: require("./equipoAbogado"),
	DetallePagoArriendo: require("./rentacar/detallePagoArriendo"),
	EgresoInmobiliaria: require("./egresoInmobiliaria"),
	respaldoEgresoInmobiliaria: require("./respaldoEgresoInmobiliaria"),
};
